---
- name: GoReplay | Ensure prerequisites are installed
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ goreplay_required_libs }}"

- name: GoReplay | Ensure goreplay group
  group:
    name: "{{ goreplay_group }}"
    system: yes
    state: present

- name: GoReplay | Ensure goreplay user
  user:
    name: "{{ goreplay_user }}"
    group: "{{ goreplay_group }}"
    system: yes
    shell: /usr/sbin/nologin
    createhome: no

- name: GoReplay | Ensure goreplay dirs exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ goreplay_user }}"
    group: "{{ goreplay_group }}"
  with_items:
    - "{{ goreplay_bin_path }}"
    - "{{ goreplay_output_path }}"

- name: GoReplay | Check goreplay version
  command: "cat {{ goreplay_installed_version }}"
  register: goreplay_check
  changed_when: false
  ignore_errors: true

- name: GoReplay | Download goreplay
  get_url:
    url: "{{ goreplay_url }}/{{ goreplay_package }}"
    dest: "{{ goreplay_package_path }}"
  when: goreplay_force_reinstall or goreplay_check is failed or goreplay_version not in goreplay_check.stdout

- name: GoReplay | Extract goreplay
  unarchive:
    src: "{{ goreplay_package_path }}"
    dest: "{{ goreplay_download_path }}"
    remote_src: True
  when: goreplay_force_reinstall or goreplay_check is failed or goreplay_version not in goreplay_check.stdout
  notify: restart goreplay

- name: GoReplay | Copy binary
  copy:
    src: "{{ goreplay_src_bin }}"
    dest: "{{ goreplay_bin_path }}/{{ goreplay_exec_name }}"
    owner: "{{ goreplay_user }}"
    group: "{{ goreplay_group }}"
    remote_src: True
    mode: 0744 # I do not want other users to be able to execute it because it can open raw sockets
  when: goreplay_force_reinstall or goreplay_check is failed or goreplay_version not in goreplay_check.stdout
  notify: restart goreplay

- name: GoReplay | Copy version number file
  template:
    src: version.txt.j2
    dest: "{{ goreplay_installed_version }}"
    owner: "{{ goreplay_user }}"
    group: "{{ goreplay_group }}"
    mode: 0644
  when: goreplay_force_reinstall or goreplay_check is failed or goreplay_version not in goreplay_check.stdout

- name: GoReplay | Link binary
  file:
    src: "{{ goreplay_bin_path }}/{{ goreplay_exec_name }}"
    dest: /usr/bin/{{ goreplay_exec_name }}
    state: link

- name: GoReplay | Ensure goreplay can open raw sockets
  command: >
    setcap "cap_net_raw,cap_net_admin+eip" {{ goreplay_bin_path }}/{{ goreplay_exec_name }}
  changed_when: false
